const skillsPerClass = {
    'Kaiser': [[60000221, 60001217, 60001216], [61001000, 61001101, 61001002, 61000003], [61100009, 61101100, 61101101, 61101002, 61101004, 61100006, 61100007, 61100005, 61100008], [], [], []]
};

// I have to manually type these
var attackSkillVars = {
    structureExample: [['attackCount'], ['damage'], ['mobCount'], ['bulletCount']],
    61001000: [['attackCount', 'v', 'z'], ['damage', 'u', 'y'], ['mobCount', 's', 'w']],
    61001101: [['attackCount'], ['damage'], ['mobCount'], ['bulletCount']]
};

const attackSequences = {
    61001000: [[61001000,[283,167],[267,118]], [61001004,[363,129],[259,104]], [61001005,[335,209],[289,147]]]
};

const attackSkillEffects = {
    61001101: {delays: [210,90,90,90,90], dimensions: [389,295], origin: [210, 176]}
};

var passiveSkillVars = {
    structureExample: {'pddX': 'defense', 'w': 'targetSkill', 'p': 'attCountX'},
    61000003: {'pddX': 'defense'},
    60000221: {},
    60001217: {'padX': 'physicalAttack'},
    60001216: {'pddX': 'defense'},
    61100009: {},
    61100008: {'padX': 'physicalAttack'},
    61100005: {'pddX': 'defense'},
    61100007: {'mhpR': 'maxHp', 'strX': 'strength'},
    61100006: {'mastery': 'mastery'}
};

var skillsThatGetEnhanced = {
    61001000: {
        61100009: {'stats': {'damageMult': 'damR'}, 'effect': 'CharLevel30effect', 'hit': 'CharLevel30hit0', 'effectDimensions': [[352,170], [369,138], [335,219]], 'hitDimensions': [237,131]}
    }
};

const classSkills = {
    60000221: {
        className: 'Kaiser',
        skillName: 'Transfiguration',
        tier: 1,
        maxLevel: 1,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Fill up your Morph Gauge in battle to transform into a more powerful being.',
        requirementText: '',
        hitDescriptions: ['#cStage 1: #Attack Speed: +1, Speed: +5, Jump: +10, Power Stance Chance: 40%', '#cStage 2: #Attack Speed: +1, Speed: +10, Jump: +20, Power Stance Chance: 80%'],
        usedVariables: {'mpCon': '0'},
        computedVars: {}
    },
    60001217: {
        className: 'Kaiser',
        skillName: 'Realign: Attacker Mode',
        tier: 1,
        maxLevel: 1,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Switches from defensive to offensive mode. Passive enhancements increase at higher Job Advancements. Skill enhancements stack.',
        requirementText: '',
        hitDescriptions: ['Attack Power: +5, Critical Rate: +3%, Boss Damage: +3%'],
        usedVariables: {'mpCon': '0', 'padX': '5', 'bdR': '3', 'cr': '3'},
        computedVars: {}
    },
    60001216: {
        className: 'Kaiser',
        skillName: 'Realign: Defender Mode',
        tier: 1,
        maxLevel: 1,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Switches from offensive to defensive mode. Passive enhancements increase at higher Job Advancements. Skill enhancements stack.',
        requirementText: '',
        hitDescriptions: ['Defense: +200'],
        usedVariables: {'mpCon': '0', 'pddX': '200'},
        computedVars: {}
    },
    61001000: {
        className: 'Kaiser',
        skillName: 'Dragon Slash',
        tier: 1,
        maxLevel: 25,
        type: 'attackSequence',
        mpCon: '0',
        ball: {},
        action: [['swingT3', 0, 90, [-1, 0]], ['swingT3', 1, 90, [-6, 0]], ['swingT3', 2, 90, [-7, 0]], ['swingT3', 2, 90, [-15, 0]], ['swingT3', 2, 90, [-15, 0]], ['swingT3', 2, 120, [-15, 0]]],
        delays: [90, 90, 90, 90],
        reuseWaitTime: 425,
        finalForm: {},
        hitDelays: [90, 90, 90, 90, 90, 90],
        hitDimensions: [187, 131],
        description: 'Mash the attack key to whip enemies in front of you up to 3 times. Can be used with basic attack key while in Final Form.',
        requirementText: 'Level 20 required to learn Dragon Slash I.',
        hitDescriptions: ['1-hit: Attack up to 8 enemies for {50+x}% damage 3 times', '2-hit: Up to 6 enemies attack for {30+x}% damage 5 times', '3-hit: Up to 6 enemies attack for {40+x}% damage 5 times', 'Final Form: Up to 8 enemies attack for {140+x}% damage 5 times, Up to 10 enemies attack 6 times after 4th job'],
        usedVariables: {'mpCon': '0', 'attackCount': '3', 'mobCount': '8', 'damage': '50+x', 'q2': '140+x', 's2': '5', 'u2': '10', 'v2': '6', 's': '6', 'u': '30+x', 'v': '5', 'w': '6', 'y': '40+x', 'z': '5', 'q': '8'},
        computedVars: {}
    },
    61001101: {
        className: 'Kaiser',
        skillName: 'Flame Surge',
        tier: 1,
        maxLevel: 25,
        type: 'ballEmitter',
        mpCon: '6+Math.ceil(x/5)',
        ball: {'dimensions': [104,63], 'delays': [90,90,90]},
        action: [['swingT1', 0, -90, [5, 0]], ['swingT1', 0, -120, [6, 0]], ['swingT1', 1, 90, [-37, 0]], ['swingT1', 2, 90, [-39, 0]], ['swingT1', 2, 90, [-40, 0]], ['swingT1', 2, 90, [-41, 0]]],
        delays: [210, 90, 90, 90, 90],
        reuseWaitTime: 507,
        finalForm: {},
        hitDelays: [90, 90, 90, 90, 90],
        hitDimensions: [160, 130],
        description: 'Blast forward with warrior spirit.',
        requirementText: '',
        hitDescriptions: ['MP Cost: {6+Math.ceil(x/5)}, Damage: {110+3*x}%, Number of Attacks: 2, Max Enemies Hit: 6'],
        usedVariables: {'mpCon': '6+Math.ceil(x/5)', 'attackCount': '2', 'mobCount': '6', 'damage': '110+3*x', 'bulletCount': '1'},
        computedVars: {}
    },
    61001002: {
        className: 'Kaiser',
        skillName: 'Air Lift',
        tier: 1,
        maxLevel: 15,
        type: 'jump',
        mpCon: '25-x',
        ball: {},
        delays: [60, 60, 60, 60, 60],
        reuseWaitTime: 267,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Grants an increase to Speed and an extra mid-air jump.',
        requirementText: '',
        hitDescriptions: ['MP Cost: {25-x}, Set Jump Distance, Max Speed: +{5+x}, Speed: +{5+x}'],
        usedVariables: {'mpCon': '25-x', 'speedMax': '5+x', 'psdSpeed': '5+x'},
        computedVars: {}
    },
    61000003: {
        className: 'Kaiser',
        skillName: 'Scale Skin',
        tier: 1,
        maxLevel: 15,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Hardens your skin to permanently increase Defense and gain a chance resist knockback. Stacks with Transfiguration\'s Knockback Resistance effects.',
        requirementText: '',
        hitDescriptions: ['DEF: +{20*x}, Knockback Resistance: +{4*x}%'],
        usedVariables: {'mpCon': '0', 'pddX': '20*x', 'prop': '4*x'},
        computedVars: {}
    },
    61001004: {
        action: [['stabOF', 2, 90, [-2, 0]], ['stabOF', 2, 90, [-4, 0]], ['stabOF', 2, 90, [-6, 0]], ['stabOF', 2, 90, [-6, 0]], ['stabOF', 2, 90, [-6, 0]], ['stabOF', 2, 120, [-6, 0]]]
    },
    61001005: {
        action: [['swingTF', 2, 90, [6, 0]], ['swingTF', 3, 90, [2, 0]], ['swingTF', 3, 90, [1, 0]], ['swingTF', 3, 90, [1, 0]], ['swingTF', 3, 90, [1, 0]], ['swingTF', 3, 120, [1, 0]]]
    },
    61100009: {
        className: 'Kaiser',
        skillName: 'Dragon Slash I',
        tier: 1,
        maxLevel: 2,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Enhances Dragon Slash\'s Attack Power. Required Skill: #cLevel 20 Dragon Slash#',
        requirementText: 'Level 2 required to learn Dragon Slash II.',
        hitDescriptions: ['Additional {20*x}% bonus to Dragon Slash damage'],
        usedVariables: {'mpCon': '0', 'damR': '20*x'},
        computedVars: {}
    },
    61101100: {
        className: 'Kaiser',
        skillName: 'Impact Wave',
        tier: 1,
        maxLevel: 20,
        type: 'attack',
        mpCon: '12+Math.floor(x/4)',
        ball: {},
        action: [['swingT3', 1, -90, [1, 0]], ['swingT3', 1, -90, [2, 0]], ['swingT3', 2, -90, [-22, 0]], ['swingT3', 2, 90, [-23, 0]], ['swingT3', 2, 90, [-24, 0]], ['swingT3', 2, 90, [-25, 0]], ['swingT3', 2, 90, [-22, 0]]],
        delays: [180, 90, 90, 90, 90, 90, 90, 90, 90],
        reuseWaitTime: 800,
        finalForm: {},
        hitDelays: [60, 60, 60, 60, 60, 60],
        hitDimensions: [1, 1],
        description: 'Stab your sword into the ground to create an explosive shockwave that blasts multiple enemies. #cCommand Skill: During Attack + Up key',
        requirementText: '',
        hitDescriptions: ['MP Cost: {12+Math.floor(x/4)}, Damage: {190+4*x}%, Mobs Hit: 8, Number of Attacks: 2'],
        usedVariables: {'mpCon': '12+Math.floor(x/4)', 'attackCount': '2', 'mobCount': '8', 'damage': '190+4*x'},
        computedVars: {}
    },
    61101101: {
        className: 'Kaiser',
        skillName: 'Piercing Blaze',
        tier: 1,
        maxLevel: 10,
        type: 'attack',
        mpCon: '10+x',
        ball: {},
        action: [['alert', 2, -90], ['swingT3', 1, 510]],
        delays: [120, 120, 90, 90, 90, 90, 90],
        reuseWaitTime: 613,
        finalForm: {},
        hitDelays: [90, 90, 90, 90],
        hitDimensions: [150, 124],
        description: 'Dash forward to knock back enemies. Deals damage to multiple targets with a chance to stun. Can be resisted by some monsters.',
        requirementText: '',
        hitDescriptions: ['MP Cost: {10+x}, Monsters Hit: 12, Damage: {160+9*x}%, Stun Chance: {20+6*x}%, Stun Duration: 2 sec'],
        usedVariables: {'mpCon': '10+x', 'mobCount': '12', 'damage': '160+9*x', 'prop': '20+6*x', 'time': '2'},
        computedVars: {}
    },
    61101002: {
        className: 'Kaiser',
        skillName: 'Tempest Blades',
        tier: 1,
        maxLevel: 20,
        type: 'flyingSwords',
        mpCon: '20+Math.ceil(x/2)',
        ball: {},
        action: [['alert', 0, 180]],
        delays: [60, 90, 90, 90, 90, 90, 90, 90, 90, 90],
        reuseWaitTime: 773,
        finalForm: {},
        hitDelays: [60, 60, 60, 60, 60, 60],
        hitDimensions: [134, 116],
        description: 'Summons 3 swords to track and attack monsters.',
        requirementText: 'Level 20 required to learn Advanced Tempest Blades.',
        hitDescriptions: ['MP Cost: {20+Math.ceil(x/2)}, Swords Summoned: 3. #cUse the skill again after summoning# to send the swords at the enemy and deal {220+4*x}% damage with 3 attacks.', 'Cooldown: 10 sec\\r', 'Final Form: Number of Attacks: +1 '],
        usedVariables: {'mpCon': '20+Math.ceil(x/2)', 'bulletCount': '3', 'attackCount': '3', 'cooltime': '10', 'damage': '220+4*x'},
        computedVars: {}
    },
    61101004: {
        className: 'Kaiser',
        skillName: 'Blaze On',
        tier: 1,
        maxLevel: 20,
        type: 'buff',
        mpCon: '10+x',
        ball: {},
        action: [['alert', 0, 150], ['alert', 1, 150], ['alert', 2, 420], ['swingT1', 1, 360]],
        delays: [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
        reuseWaitTime: 1200,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Draw out inner strength to temporarily increase Attack Power and Speed.',
        requirementText: '',
        hitDescriptions: ['MP Cost: {10+x}, Duration: {12*x} sec, Attack Power: +{x}, Attack Speed: +2'],
        usedVariables: {'mpCon': '10+x', 'indiePad': 'x', 'time': '12*x'},
        computedVars: {}
    },
    61100006: {
        className: 'Kaiser',
        skillName: 'Sword Mastery',
        tier: 1,
        maxLevel: 10,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Increases two-handed sword weapon mastery and accuracy.',
        requirementText: 'Level 10 required to learn Expert Sword Mastery.',
        hitDescriptions: ['Two-Handed Sword Mastery: +{10+4*x}%'],
        usedVariables: {'mpCon': '0', 'mastery': '10+4*x'},
        computedVars: {}
    },
    61100007: {
        className: 'Kaiser',
        skillName: 'Inner Blaze',
        tier: 1,
        maxLevel: 10,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Increases Strength and HP.',
        requirementText: 'Level 10 required to learn Advanced Inner Blaze.',
        hitDescriptions: ['STR: +{2*x}, HP: +{2*x}%'],
        usedVariables: {'mpCon': '0', 'strX': '2*x', 'mhpR': '2*x'},
        computedVars: {}
    },
    61100005: {
        className: 'Kaiser',
        skillName: 'Defender Mode I',
        tier: 1,
        maxLevel: 1,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Enhances Realign: Defender Mode. Enhanced effects stack.',
        requirementText: 'Level 1 required to learn Defender Mode II.',
        hitDescriptions: ['Defense: Additional +200'],
        usedVariables: {'mpCon': '0', 'pddX': '200'},
        computedVars: {}
    },
    61100008: {
        className: 'Kaiser',
        skillName: 'Attacker Mode I',
        tier: 1,
        maxLevel: 1,
        type: 'passive',
        mpCon: '0',
        ball: {},
        delays: [],
        reuseWaitTime: 0,
        finalForm: {},
        hitDelays: [],
        hitDimensions: [],
        description: 'Further enhances Realign: Attacker Mode. Enhanced effects stack.',
        requirementText: 'Level 1 required to learn Attacker Mode II.',
        hitDescriptions: ['Attack Power: +10, Critical Rate: +2%, Boss Damage: +5%'],
        usedVariables: {'mpCon': '0', 'padX': '10', 'bdR': '5', 'cr': '2'},
        computedVars: {}
    }
};
